FROM node:20-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo da aplicação para o diretório de trabalho
COPY app.js .

# RUN npm install

# Defina o comando para executar a aplicação quando o contêiner iniciar
CMD ["node", "app.js"]
